/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 aspire.glb -t -i -T -f 
Files: aspire.glb [2.69MB] > D:\Duvan\portfolio-cbtic\public\Models\lawfaraday\aspire-transformed.glb [66.79KB] (98%)
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { PATH_LAW_FARADAY } from "@/config";

type GLTFResult = GLTF & {
  nodes: {
    ASPIRE: THREE.Mesh;
  };
  materials: {
    ASPIRE: THREE.MeshStandardMaterial;
  };
  //animations: GLTFAction[]
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    PATH_LAW_FARADAY + "/aspire-transformed.glb",
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.ASPIRE.geometry}
        material={materials.ASPIRE}
        position={[0, 0, -467.917]}
        scale={266.618}
      />
    </group>
  );
}
