/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 iman.glb -t -i -T -f 
Files: iman.glb [11.91MB] > D:\Duvan\portfolio-cbtic\public\Models\lawfaraday\iman-transformed.glb [394.85KB] (97%)
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { PATH_LAW_FARADAY } from "@/config";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { useMove } from "@store";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    IMANC: THREE.Mesh;
    IMANC_1: THREE.Mesh;
    IMANC_2: THREE.Mesh;
    FIELD_IMAN: THREE.Mesh;
  };
  materials: {
    NORTE: THREE.MeshStandardMaterial;
    SUR: THREE.MeshStandardMaterial;
    LETRAS: THREE.MeshStandardMaterial;
    Emission: THREE.MeshStandardMaterial;
  };
  // animations: GLTFAction[];
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const refIman = useRef<THREE.Group>(null!);
  const { nodes, materials } = useGLTF(
    PATH_LAW_FARADAY + "/iman-transformed.glb",
  ) as GLTFResult;

  useFrame((state, delta, xrFrame) => {
    // This function runs at the native refresh rate inside of a shared render-loop
    if (useMove.getState().moveX) {
      // 0.1 es el factor de interpolación
      const state = useMove.getState();
      const targetX = state.moveX;
      const currentX = refIman.current.position.z;
      refIman.current.position.z = THREE.MathUtils.lerp(currentX, targetX, 0.1);
    }
  });
  return (
    <group {...props} dispose={null} ref={refIman}>
      <mesh
        geometry={nodes.IMANC.geometry}
        material={materials.NORTE}
        rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
        scale={[100, 199.717, 100]}
      />
      <mesh
        geometry={nodes.IMANC_1.geometry}
        material={materials.SUR}
        rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
        scale={[100, 199.717, 100]}
      />
      <mesh
        geometry={nodes.IMANC_2.geometry}
        material={materials.LETRAS}
        rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
        scale={[100, 199.717, 100]}
      />
      <mesh
        geometry={nodes.FIELD_IMAN.geometry}
        material={materials.Emission}
        position={[0, 34.413, -682.811]}
        rotation={[2.561, 0, 0]}
        scale={12.933}
      />
    </group>
  );
}


