import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Navbar } from "@/components";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="w-full h-screen">
          <Navbar />
          <main className="w-full h-[90%] bg-[#f8f8f8]">{children}</main>
        </main>
      </body>
    </html>
  );
}
